
public class Foo {
  public void duplicatedFunction(List<String> args) {
    System.debug('hello world1');
    Integer a = 0;
    a = a + 1;
    System.debug('hello world2');
    a = 0;
    a = a + 1;
    System.debug('hello world3');
    a = 0;
    a = a + 1;
    System.debug('hello world4');
    a = 0;
    a = a + 1;
    System.debug('hello world2');
    a = 0;
    a = a + 1;
    System.debug('hello world3');
    a = 0;
    a = a + 1;
    System.debug('hello world4');
    a = 0;
    a = a + 1;
  }

}

