name: Build
on:
  push:
    branches:
      - master
      - branch-*
      - SONARGO-669
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

env:
  GO_VERSION: "1.25.1"
  GOLANG_CI_LINT_VERSION: "2.4.0"
  ARCH: amd64
  SONAR_PROJECT_KEY: "SonarSource_sonar-go"

jobs:
  build_test_sonar:
    runs-on: sonar-s-public
    name: Build
    permissions:
      id-token: write  # Required for Vault OIDC authentication
      contents: write  # Required for repository access and tagging
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: jdx/mise-action@e3d7b8d67a7958d1207f6ed871e83b1ea780e7b0 # v3.3.1
        with:
          version: 2025.7.12
      - name: Install golangci-lint
        run: |
          curl --proto "=https" -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /home/runner/go/bin v${GOLANG_CI_LINT_VERSION}
          echo "/opt/go/bin:/opt/protoc/bin:/opt/musl/bin:/home/runner/go/bin" >> $GITHUB_PATH
      - name: Checkout build logic
        run: |
          git submodule update --init --depth 1 -- build-logic/common
      - name: Create Gradle User Home
        shell: bash
        run: |
          export GRADLE_USER_HOME=${GITHUB_WORKSPACE}/.gradle
          mkdir -p ${GRADLE_USER_HOME}
          echo "GRADLE_USER_HOME=${GRADLE_USER_HOME}" >> $GITHUB_ENV
          export TODAY=$(date '+%Y-%m-%d')
          echo "TODAY=${TODAY}" >> $GITHUB_ENV
          find . -name '*.gradle.kts' -type f -exec md5sum {} \; | sort && md5sum gradle/libs.versions.toml && md5sum gradle/wrapper/gradle-wrapper.properties && md5sum gradle.properties > gradle-md5-sums.txt 
          export GRADLE_CACHE_KEY=$(md5sum gradle-md5-sums.txt | awk '{ print $1 }')
          echo "GRADLE_CACHE_KEY=${GRADLE_CACHE_KEY}" >> $GITHUB_ENV
          rm gradle-md5-sums.txt
      - name: Cache Gradle Dependencies
        uses: SonarSource/ci-github-actions/cache@v1
        with:
          path: ${{ env.GRADLE_USER_HOME }}
          key: gradle-${{ env.GRADLE_CACHE_KEY }}
      - name: Create Go cache keys
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          export GOCACHE=$(go env GOCACHE)
          echo "GOCACHE=${GOCACHE}" >> $GITHUB_ENV
          export GOCACHE_KEY=$(find ${GITHUB_WORKSPACE}/sonar-go-to-slang -name '*.go' -o -name 'go.mod' -o -name 'go.sum' -exec cat {} + | sha256sum | xargs echo $RUNNER_OS $RUNNER_ARCH | tr -s ' ' '-')
          echo "GOCACHE_KEY=${GOCACHE_KEY}" >> $GITHUB_ENV
      - name: Cache Go Build
        uses: SonarSource/ci-github-actions/cache@v1
        if: ${{ env.GO_CACHE_ENABLED }}
        with:
          path: ${{ env.GOCACHE }}
          key: ${{ env.GOCACHE_KEY }}

      - uses: SonarSource/ci-github-actions/build-gradle@v1
        env:
          GO_CROSS_COMPILE: 1
        with:
          public: true
          deploy-pull-request: false
          skip-tests: false
          use-develocity: true
          gradle-args: "--build-cache --configuration-cache -x artifactoryPublish"
          disable-caching: true
          run-shadow-scans: true

      - name: Run IRIS Analysis
        uses: SonarSource/unified-dogfooding-actions/run-iris@v1
        with:
          primary_project_key: ${{ env.SONAR_PROJECT_KEY }}
          primary_platform: "Next"
          shadow1_project_key: ${{ env.SONAR_PROJECT_KEY }}
          shadow1_platform: "SQC-EU"
          shadow2_project_key: ${{ env.SONAR_PROJECT_KEY }}
          shadow2_platform: "SQC-US"
